
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gbdcxpanbwvldanarioo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZGN4cGFuYnd2bGRhbmFyaW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxODk2NTgsImV4cCI6MjA2MTc2NTY1OH0.aKPEc6pyKDUyyukRJpbxPlhytbhMNjGCwsE9Edq1sdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
